# Generated by Django 4.1.2 on 2022-10-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
