# Generated by Django 4.1.2 on 2022-10-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='follower',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
