# Generated by Django 4.1.2 on 2022-10-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_registered_follower_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='approved',
        ),
    ]
