# Generated by Django 4.1.2 on 2022-10-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_inboxitem_type_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image_url',
            field=models.TextField(default='https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png'),
        ),
    ]
