# Generated by Django 4.1.2 on 2022-11-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_remotenode_base_url_alter_remotenode_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotenode',
            name='home_page',
            field=models.TextField(default='#', unique=True),
        ),
    ]
