# Generated by Django 4.1.2 on 2022-12-03 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remotenode_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
