# Generated by Django 4.1.2 on 2022-12-05 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_inboxitem_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='friends_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
    ]
