# Generated by Django 4.1.2 on 2022-12-05 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_inboxitem_friends_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxitem',
            name='friends_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
    ]
